### ISSUE TITLE
add reverse spread operator

### ISSUE THREAD

**Issue by drupol** [ara-lang/parser#17]
Hey hi !

Following [our discussion on Mastodon](https://mathstodon.xyz/@Pol/109635727698522337), I'm opening this issue to discuss a new feature.

The idea would be to have a spread operator, but in reverse direction.

Just like we have the spread operator which spread from the left to the right:

```php
$a = range(0, 3);
var_dump(...$a); // Print 0, 1, 2, 3
```

We could have:

```php
$a = range(0, 3);
var_dump($a...); // Print 3, 2, 1, 0
```

This reverse operator would spread an iterable from the right to the left.

Let me know what you think about this idea, this is something that would be very cool to have !

Thanks!

**Comment by azjezz** [comment]
I think you mean

```
$a = range(0, 3);
var_dump($a...); // Print 3, 2, 1, 0
```

https://3v4l.org/2o0qU

**Comment by drupol** [comment]
Yup indeed, I fixed my original message for less confusion.

**Comment by azjezz** [comment]
done ✔️

**Comment by azjezz** [comment]
note: just like the normal spread arguments, reverse spread arguments can't be used in constant expressions.


see: https://github.com/ara-lang/parser/commit/4a781f31e343e15660d4e165bb437e9271a0796d#diff-fcefe4cbaff3c20970310dcdc0805199d85d04b75e5d643d0ce3cf01ced2dd4b

and: https://github.com/ara-lang/parser/commit/4a781f31e343e15660d4e165bb437e9271a0796d#diff-a7eac1cd62ff44bf6e61280cb2cfcee1d21716dd6b017c43394a56c2fc34c60d

**Comment by drupol** [comment]
Nice one !!!
